### ISSUE TITLE
Depend on python-dateutil >= 2.8.0 for 2.x

### ISSUE THREAD

**Issue by warmwaffles** [SectorLabs/django-postgres-extra#93] opened 2020-02-14 19:25 UTC
Locally I have 2.8.1 installed and as long as we have above 2.8 this library should be satisfied.

I can add it to the requirements if that would make this easier for you guys.

**Comment by Photonios** [comment] 2020-03-27 07:18
This is a duplicate of #92 .

**Closed by Photonios** 2020-03-27 07:18 UTC
