### ISSUE TITLE
bulk_insert doesn't set database on objects

### ISSUE THREAD

**Issue by Amoki** [SectorLabs/django-postgres-extra#64] opened 2018-08-16 15:38 UTC
```python
class Extensions(PostgresModel):
    topic_type = models.ManyToManyField("TopicType", blank=True)


class TopicType(PostgresModel):
    topic_type = models.CharField(max_length=255, unique=True)

ext = Extensions.objects.create()
topic_types = TopicType.objects.on_conflict(
    ["topic_type"], ConflictAction.UPDATE
).bulk_insert([{"topic_type": "information"}, {"topic_type": "error"}], return_model=True)
ext.topic_type.add(*topic_types)
# Raises ValueError: Cannot add "<TopicType: information>": instance is on database "default", value is on database "None"
```

Forcing a `.save()` on all objects returned by `bulk_insert` works.
I'm using 1.21a12

EDIT: Oh, it may be a duplicate of https://github.com/SectorLabs/django-postgres-extra/issues/25

**Comment by Photonios** [comment] 2019-03-14 08:43
Yeap, closing this as a duplicate of #25.

**Closed by Photonios** 2019-03-14 08:43 UTC
